spring:
  application:
    name: basic-project-skeleton
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://db-demo.c9qq8ucagixn.us-east-1.rds.amazonaws.com:3306/demo?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    password: asdacmdk27123

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false