name: CI Demo

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Imprimiendo algo
        run: echo "hola mundo GA"
      - name: Muestra el contenido del directorio
        run: ls -la
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - run: java --version
      - run: chmod +x mvnw
      - name: Build with Maven
        run: ./mvnw clean package --file pom.xml -DskipTests
      - name: Listar jar
        run: ls -la target
      - name: Instalar docker
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      - name: Docker login
        run: echo "asdacmdk27" | docker login -u jesuscar --password-stdin
      - name: Build Docker image
        run: docker build -t jesuscar/ci-demo .